### ISSUE TITLE
CKEDITOR not working on production

### ISSUE THREAD

**Issue by gusarg81** [django-ckeditor/django-ckeditor#425] opened 2017-09-02 19:28 UTC
I have a weird problem, django-ckeditor is not working on production. I mean, there is not error at all (not even in browser debug) or django logs. But is working on my local develoment.

- In production, I use apache2+mod_wsgi for my django site.
- In local development, just django webserver.

Versions (in both places, are the same):

django-ckeditor: v5.3.0
django: 1.11.4

I set the ckeditor widget in ModelForm. Example:

> class ServicesForm(forms.ModelForm):
> 	class Meta:
> 		model = Services
> 		fields = "__all__"
> 		
> 		widgets = {
> 			"description": CKEditorWidget()
> 		}

And inside template:

> {% load static %}
> 
> <form id='services-form' action='' method='post' enctype='multipart/form-data'>
> 	{% csrf_token %}
> 	{{ services_form.media }}
> 	{{ services_form.as_p }}
> 	{{ services_form.errors.as_p }}
> </form> 

Also, i've already issued "python3 manage.py collectstatic" (as I said, there is not JS or CSS errors on browser. I can open directly the JS of ckeditor in the browser inside production.)

I don't know if related or not, but all forms in my project I call them using ajax (but as I said, works perfectly in local development).

I didn't have problems in the past with other projects, so I don't have a clue what is going on.

Any ideas? Thanks in advance.

**Comment by gusarg81** [comment] 2017-09-04 01:14
Add: I also found that in my local development only works with Chrome, and not showing the editor in Firefox.

**Comment by LegoStormtroopr** [comment] 2017-09-04 01:22
See #426

**Comment by gusarg81** [comment] 2017-09-04 02:51
Hi, Pillow is already installed on local and production. Also it does not explain why on local only works on Chrome and not on Firefox.

**Comment by matthiask** [comment] 2017-09-04 07:14
There was a regression with the rewrite of `ckeditor-init.js` without jQuery which has been fixed in https://github.com/django-ckeditor/django-ckeditor/commit/81320254b6e4949499e688c55404343be3f105ee, but the fix hasn't been released yet. Maybe that is the problem.

(You could maybe fix this by dropping the `ckeditor/ckeditor-init.js` file from the master branch in one of your `STATICFILES_DIRS` so that the newer version overrides the version in the release when running `collectstatic`.)

**Comment by gusarg81** [comment] 2017-09-04 13:18
Hi,
    It didn't work either (testing in local development), having the same beehaviour: working on chrome, not working on firefox:

Chrome: http://imgur.com/a/Pyk1g
Firefox: http://imgur.com/a/enRTG

I didn't tested in production, since is not working well either in local.

**Comment by gusarg81** [comment] 2017-09-04 16:43
Add: also tested django-ckeditor 5.2.2 and I have the same problem. How I can fix temporary this? By intalling older Django than 1.11.4? Because I also tested django-ckeditor 5.0.0 but I have this other problem:

  File "/usr/local/lib/python3.5/dist-packages/ckeditor/widgets.py", line 111, in render
    final_attrs = self.build_attrs(attrs, name=name)
TypeError: build_attrs() got an unexpected keyword argument 'name'

Thanks in advance.

**Comment by gusarg81** [comment] 2017-09-04 17:05
Hi, sorry for too many posts... I think the problem is mine, I've tested the demo and is working fine in Firefox and Chrome. So, I don't know what is going on :(

**Comment by gusarg81** [comment] 2017-09-04 20:45
More crazy stuff: everything is working on my notebook (anoter computer I use for development) in Chrome and Firefox. I have the same versions of Django and Django-ckeditor and of course the django project (even i just cleaned all packages in both computers and reinstalled all deps again, still in my main computer is not working and now is not working in Chrome either). I can't tell why in my notebook does work...

Besides pillow, is there any other dependencies I should aware off?

**Comment by b2scrip** [comment] 2018-08-09 00:58
Hi,
It didn't work either (testing in local development), having the same beehaviour: working on chrome, not working on firefox:

Chrome: http://imgur.com/a/Pyk1g
Firefox: http://imgur.com/a/enRTG

I didn't tested in production, since is not working well either in local.

**Comment by gusarg81** [comment] 2018-08-09 15:04
Hi!

I just ended by using django-tinymce4-lite.
Saluda ATTE.
-- 

Gustavo A. Díaz
GDNet - www.gdnet.com.ar (http://www.gdnet.com.ar/)
"Servicios TI para tus necesidades"
Tel. (011) 2063-8252
Cel. 15-6469-7064

8 de agosto de 2018 21:59, "b2scrip" <notifications@github.com (mailto:notifications@github.com?to=%22b2scrip%22%20<notifications@github.com>)> escribió:
	Hi,
It didn't work either (testing in local development), having the same beehaviour: working on chrome, not working on firefox: 

	Chrome: http://imgur.com/a/Pyk1g (http://imgur.com/a/Pyk1g)
Firefox: http://imgur.com/a/enRTG (http://imgur.com/a/enRTG) 

	I didn't tested in production, since is not working well either in local.

**Closed** 2023-05-23 10:34 UTC
Labels: no-issue-activity
