### ISSUE TITLE
TypeError: unhashable type: 'JS'

### ISSUE THREAD

**Issue by sSimuSs** [django-ckeditor/django-ckeditor#574] opened 2019-11-06 09:53 UTC
```
from ckeditor.fields import RichTextField

class MyModel(models.Model):
    title = models.CharField(max_length=255)
    content = RichTextField(blank=True, null=True)
```
python: 3.7
django: 2.2.3

**Comment by matthiask** [comment] 2019-11-06 12:33
Probably a duplicate of https://github.com/django-ckeditor/django-ckeditor/issues/568

**Closed** 2019-11-06 12:50 UTC
