### ISSUE TITLE
Fix RemovedInDjango20Warning: Importing from django.core.urlresolvers is deprecated in favor of django.urls.

### ISSUE THREAD

**Issue by lorddaedra** [django-ckeditor/django-ckeditor#451] opened 2017-12-03 23:34 UTC
```➜  src git:(develop) ✗ docker exec expo-test /usr/local/bin/python3 -u -Wall /usr/src/app/manage.py check
/usr/local/lib/python3.6/site-packages/ckeditor_uploader/widgets.py:1: RemovedInDjango20Warning: Importing from django.core.urlresolvers is deprecated in favor of django.urls.
  from django.core.urlresolvers import reverse```

**Comment by karolyi** [comment] 2017-12-05 11:58
here's the result of this warning in django 2.0:

```python
  File "..../venv/lib/python3.6/site-packages/ckeditor_uploader/widgets.py", line 1, in <module>
    from django.core.urlresolvers import reverse
ModuleNotFoundError: No module named 'django.core.urlresolvers'
```

**Comment by matthiask** [comment] 2017-12-05 12:31
Duplicate of #452

**Closed by matthiask** 2017-12-05 12:31 UTC
