### ISSUE TITLE
ckeditor4 end of life

### ISSUE THREAD

**Issue by goapunk** [django-ckeditor/django-ckeditor#745] opened 2023-06-14 07:53 UTC
Hi everyone,
thanks for maintaining this project! As recently announced ckeditor4 is end of life since June (https://ckeditor.com/blog/ckeditor-4-end-of-life/). Are there any plans to move to ckeditor5 ? Or would you be accepting PRs for that?

Cheers

**Comment by matthiask** [comment] 2023-06-14 07:55
That's a duplicate of https://github.com/django-ckeditor/django-ckeditor/issues/482

Let's continue the discussion over there!

**Closed by matthiask** 2023-06-14 07:55 UTC
