### ISSUE TITLE
Can I restrict max uploaded file size?

### ISSUE THREAD

**Issue by Mike667** [django-ckeditor/django-ckeditor#418] opened 2017-07-30 15:13 UTC
Can I restrict max uploaded file size from Django admin?

**Comment by matthiask** [comment] 2017-07-31 06:53
Duplicate of https://github.com/django-ckeditor/django-ckeditor/issues/249 

(Yes you can, via limiting the max size for requests in nginx/apache/whatever, but not inside django-ckeditor.)

**Closed by matthiask** 2017-07-31 06:53 UTC
