### ISSUE TITLE
ckeditor is incompatible with ManifestStaticFilesStorage

### ISSUE THREAD

**Issue by SalahAdDin** [django-ckeditor/django-ckeditor#192] opened 2015-05-25 04:15 UTC
Hi guys, i have now an error with django-ckeditor 4.4.8 in my web server.

The webserver is webfaction, and my problem is the next:
I was using ckeditor in my page and work's fine, i have 4.4.7 and then updated for 4.4.8, i don't remember if i restarted the server but ckeditor works fine.
Then, i restarted the server and i try to used ckeditor but i couldn't see anything, see:
![granproblemackeditor](https://cloud.githubusercontent.com/assets/5034215/7791756/f65c2268-026b-11e5-908d-1f9f5fe22562.png)

I tried all things that i think, re collect static files, re put ckeditor urls in urls.py, all, but, nothing working.

But, in local server work fine, shure, doesn't used collecstatic, don't need it, but in the server doesn't works this.

Finally, i installed 4.4.7 and works again.
![granproblema2](https://cloud.githubusercontent.com/assets/5034215/7791816/c86a0310-026c-11e5-8239-a11b44a6a379.png)

Compare the urls from the bugs in the before image and see here:
![granproblema2](https://cloud.githubusercontent.com/assets/5034215/7791852/49a89f04-026d-11e5-9f7a-e1a2ead0e4d7.png)

The source are correct loading in this case, correct url, but, with 4.4.8 the statics urls are wrong.

Then, i think that is the problem of 4.4.8 with static urls, but, i don't know why.

Can anyone fix it?

**Comment by riklaunim** [comment] 2015-05-25 06:11
Looks like no slash at the beginning of the path. The change made to URL generation of JS files was this one: https://github.com/django-ckeditor/django-ckeditor/commit/23b8a2ec1478162f96b7677c2d40194d5dcdd62c and it should work if your STATIC_URL is correctly set.

**Comment by SalahAdDin** [comment] 2015-05-25 06:36
No, the problem is that first part of url is wrong, news/new/.../static isn't correct, the correct ist static/static/...

**Comment by riklaunim** [comment] 2015-05-25 07:30
if the src is ="static/foo/bar.js" then it will be relative path which is wrong. if it would be "/static/foo/bar.js" then it should work correctly. What's the actual path in the raw HTML?

**Comment by SalahAdDin** [comment] 2015-05-26 00:46
I don't understand your question.
I saw that ckeditor put the urls as page's url childs, in this case, news/new/ckeditor...., and these isn't the correct url.

**Comment by riklaunim** [comment] 2015-05-26 06:46
Open the page source and check how they look. I have the latest version deployed in few places and all static files are working correctly. I assume you have something wrong with STATIC_URL - so check in the source, not in the rendered  DOM what's the URL. and check/post what's your STATIC_URL.

**Comment by SalahAdDin** [comment] 2015-05-26 07:42
Wow, for now i can't do this, i fix the problem downgraded my django-ckeditor version, but tomorrow i try replicate this issue, thank you.

**Comment by riklaunim** [comment] 2015-05-26 21:05
you can even do it without installing the new version. You can test the static() and STATIC_ROOT code example in manage.py/django-admin shell

**Comment by SalahAdDin** [comment] 2015-05-27 00:09
```bash
STATICFILES_DIRS = ('/home/salahaddinal/webapps/tiempoturco/tiempoturco/statics',)
STATICFILES_STORAGE = 'django.contrib.staticfiles.storage.CachedStaticFilesStorage'
STATIC_ROOT = '/home/salahaddinal/webapps/tiempoturco_static/static'
STATIC_URL = '/static/static/'
```

I have this.

**Comment by rafaelhdr** [comment] 2015-06-02 14:56
I had the same problem of the field no showing.
It worked when i added DefaultStorageFinder on settings.py
(i don't know why)

```
STATICFILES_FINDERS = (
     'django.contrib.staticfiles.finders.FileSystemFinder',
     'django.contrib.staticfiles.finders.AppDirectoriesFinder',
-    #'django.contrib.staticfiles.finders.DefaultStorageFinder',
+    'django.contrib.staticfiles.finders.DefaultStorageFinder',
 )
```

**Comment by riklaunim** [comment] 2015-06-02 15:03
If you have a custom storage then it's likely it will need its own finder too.

I'll also check if there isn't any CachedStaticFilesStorage regressions in the latest release.

**Comment by SalahAdDin** [comment] 2015-06-02 19:16
Ok, i will put the DefaultStorageFinder in my settings and try if works, thanks.

**Comment by SalahAdDin** [comment] 2015-06-05 03:12
Ok, don't work yet.
See please:
![continua el problema](https://cloud.githubusercontent.com/assets/5034215/7998774/cacb0f30-0b06-11e5-8400-8e4c31a5809f.png)
You can see my settings and the wrong urls.

**Comment by SalahAdDin** [comment] 2015-06-05 04:10
And now i have this issue:
```ValueError: The file 'ckeditor/ckeditor/ckeditor.js' could not be found with <django.contrib.staticfiles.storage.CachedStaticFilesStorage object at 0x7ff321c585c0>.
```

I delete all static files and try collect it again, and, see.

**Comment by riklaunim** [comment] 2015-06-05 09:37
I think you need slash on the end of STATIC_ROOT - https://docs.djangoproject.com/en/1.8/ref/settings/#std:setting-STATIC_ROOT

**Comment by SalahAdDin** [comment] 2015-06-06 00:34
Ok, i'll try with this.

**Comment by SalahAdDin** [comment] 2015-06-06 06:35
![continua el problema](https://cloud.githubusercontent.com/assets/5034215/8018636/3f925720-0bec-11e5-8fe9-436eced43afb.png)

Don't works yet.

**Comment by alito** [comment] 2015-06-07 15:13
I am seeing this too. It can only be seen if DEBUG is False otherwise static takes a shortcut.

Note that the ckeditor.js and ckeditor-init.js get found fine, it's config.js that is not found. This is because the 'static' call transforms the name to eg ckeditor.677756974519.js (hashes so as not to serve a stale version when updates exist), so if ckeditor is relying on its name to be ckeditor.js to find config.js, this will trip it up.

The quick solution for those that are hitting this is to revert 23b8a2e and go back to the STATIC_URL version. Longer term would be to modify ckeditor.js to be smarter in how it finds its dependencies

**Comment by riklaunim** [comment] 2015-06-07 17:23
So it's not as easy as it looked like.

**Comment by riklaunim** [comment] 2015-06-07 17:25
Reverted in master.

**Comment by SalahAdDin** [comment] 2015-06-07 19:38
it's seems very difficult but, will be better use static but search the way for fix this bug.
Thank you man.

**Comment by SalahAdDin** [comment] 2015-06-25 03:49
is there any update here?

**Comment by riklaunim** [comment] 2015-06-25 06:17
What update do you expect? At the moment no changes here. When I'll find some time I'll do some work on this package (there is a nice todo list).

**Comment by SalahAdDin** [comment] 2015-06-25 06:35
Oh yes, but, i was talking about the problem with change static_url gettin.

**Comment by riklaunim** [comment] 2015-07-07 18:31
It's hard to reproduce that config.js error with development server. Maybe circus/dj-static test setup could help test that.

**Comment by sebsheep** [comment] 2016-04-29 16:50
It seems I have the same problem here. If `debug = True`, then all is ok, otherwise ckeditor.js, ckeditor-init.js are founded but not config.js (since the requested path by my browser is `<current_path>/config.js` instead of `static/ckeditor/ckeditor/config.js`).

I'm using the version 5.0.3 from pip, my relevant (I think) config vars are:

```
STATICFILES_STORAGE = 'whitenoise.django.GzipManifestStaticFilesStorage' # just copy-pasted from Heroku dev center, I don't really understand what does it mean
PROJECT_ROOT = os.path.dirname(os.path.abspath(__file__))
STATIC_ROOT = os.path.join(PROJECT_ROOT, 'staticfiles')
STATIC_URL = '/static/'
# Extra places for collectstatic to find static files.
STATICFILES_DIRS = (
    os.path.join(PROJECT_ROOT, 'static'),
)
```

Reading this thread, I feel this is the same problem as mine, but I didn't see any workaround for my issue.

**Comment by macolo** [comment] 2017-01-20 21:55
@SalahAdDin can you maybe rename this issue to something more descriptive?

I suggest `ckeditor is incompatible with ManifestStaticFilesStorage`?

For all the guys out there that run into the same issue and turn to Google for help...

**Comment by macolo** [comment] 2017-01-20 22:01
the changelog for 5.2.0 has a fix for `ManifestStaticFilesStorage` but I don't see this working (using 5.2.1).

https://github.com/django-ckeditor/django-ckeditor/blob/master/CHANGELOG.rst
```
5.2.0
-----
#. Django 1.10 updates
#. Development dependencies bump
#. CKEditor 4.6.1
#. Paste image support
#. Fix for ManifestStaticFilesStorage
```

**Comment by Flimm** [comment] 2017-04-18 09:59
The fix in release 5.2.2 still doesn't work for me. See my comment in pull request #377 .

**Comment by matthiask** [comment] 2017-04-23 11:40
This will be fixed in the next release. Please test the `master` branch (if you can) and report any problems in this issue tracker.

Thanks!

**Closed by matthiask** 2017-04-23 11:40 UTC

**Comment by Flimm** [comment] 2017-04-24 11:30
I just tried commit 2aaff4ed and it still has problematic Javascript code that attempts to read an HTML attribute before the DOM element has been loaded yet.

However, I followed the instructions in the new documentation committed in e080a82914bd23,  and that seemed to work for me!

**Comment by matthiask** [comment] 2017-04-24 11:41
Hmm, so you're saying that the code in `ckeditor-init.js` is running before the script tag with ID `ckeditor-init-script` (which references `ckeditor-init.js`!) is available to the DOM? That's really surprising! Do you have additional details about your environment that could help reproduce this?

**Comment by Flimm** [comment] 2017-04-24 11:49
@matthiask Ah, sorry, I just realised that I was actually testing 5.2.2. (For some reason, the deployment script I'm using didn't recognise a `git+https://` dependency in `requirements.txt`.) I just tried out the new code on my development machine and it seems to work. Good work!

**Comment by matthiask** [comment] 2017-04-24 11:53
Great, thanks for testing!

**Comment by Tanishk-Sharma** [comment] 2021-04-21 21:02
[e080a82](https://github.com/django-ckeditor/django-ckeditor/commit/e080a82914bd23377a15a4f7edb0b6eb0ab50b38)  has worked for me as well. Both in Development and in Production.
Production: heroku, gunicorn, whitenoise
using django-ckeditor==6.0.0
