### ISSUE TITLE
Source editor text is not readable in dark mode

### ISSUE THREAD

**Issue by Salaah01** [django-ckeditor/django-ckeditor#741] opened 2023-04-19 02:51 UTC
I have the editor in my admin page.
In my models I have defined a field as such:

```python
from ckeditor.fields import RichTextField

class ScheduledEmail(models.Model):
    ....
    html_message = RichTextField()
```

The editor therefore appears in the admin page, but when I try to enter source mode, the text is not readable. Screenshot attached.

![Capture](https://user-images.githubusercontent.com/48691708/232953956-911be5c2-bc14-4cc3-8232-fafbde925c40.JPG)

**Comment by hashlash** [comment] 2023-04-19 07:23
You might want to check #670

**Comment by matthiask** [comment] 2023-04-19 07:27
Right, that's a duplicate of #670. Thanks for the report!

**Closed by matthiask** 2023-04-19 07:27 UTC
