### ISSUE TITLE
Update CkEditor to Version 5 for support like code block

### ISSUE THREAD

**Issue by mnislam01** [django-ckeditor/django-ckeditor#645] opened 2021-01-03 11:15 UTC

**Comment by matthiask** [comment] 2021-01-03 12:48
Thanks for the report. This is a duplicate of https://github.com/django-ckeditor/django-ckeditor/issues/482

**Comment by matthiask** [comment] 2021-01-03 12:48
Duplicate of #482

**Closed by matthiask** 2021-01-03 12:48 UTC
