### ISSUE TITLE
ValueError: I/O operation on closed file

### ISSUE THREAD

**Issue by jonasspott** [django-ckeditor/django-ckeditor#550] opened 2019-05-09 12:31 UTC
Hi guys

This bug occurs in **version 5.7 of django-ckeditor** on both **Django 2.2.* and Django 2.1.***.

I'm getting an error when trying to upload an image through the editor.

### Error on Sentry
![image](https://user-images.githubusercontent.com/3172302/57453255-31d84b00-7266-11e9-90bd-c0edff18c885.png)

### Image trying to upload:
![image](https://user-images.githubusercontent.com/3172302/57453264-3a308600-7266-11e9-8622-bc99d6e42af1.png)

### Specs of the image
![image](https://user-images.githubusercontent.com/3172302/57453406-a0b5a400-7266-11e9-9ed9-31eda47ca414.png)

### Solution?
I'm not quite sure how to get this one solved. Anyone else seeing this problem or know how to solve it?

Jonas

**Comment by K0Te** [comment] 2019-05-28 09:31
Hi,

I've faced same issue, looks like regression between 5.6.1 and 5.7.0, also doesn't work on 5.7.1

**Comment by matthiask** [comment] 2019-05-28 09:43
I had a similar problem in django-imagefield where such errors were suddenly starting to show up. 

It may be a good idea to work on a copy of the uploaded file instead so that closing the copy does not close the original and cause crashes in Django.

(Commit in django-imagefield -- https://github.com/matthiask/django-imagefield/commit/567c4c235afa0fa3b9474c8099d97bc71dd89335)

**Closed** 2023-05-11 10:34 UTC
Labels: no-issue-activity
